#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/goinstant/pods-specs-public'

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SafeCircle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoEnhancer

  pod 'ProgressHUD', '~> 13.7.2'
  pod 'FirebaseDatabase'
  pod 'Firebase/Analytics'
  pod 'FBSDKCoreKit', '~> 8.0.0'
  pod 'FBSDKLoginKit', '~> 8.0.0'
  pod 'FBSDKShareKit', '~> 8.0.0'
  pod 'Firebase/RemoteConfig'

end
